plugins:
  zendesk_url:
    default: https://your-url.zendesk.com/api/v2
    client: true
  zendesk_enabled:
    default: false
    client: true
  zendesk_jobs_api_token:
    default: ''
    secret: true
  zendesk_jobs_email:
    default: ''
  zendesk_enabled_categories:
    type: category_list
    client: false
    default: ''
  zendesk_job_push_all_posts:
    default: true
  sync_comments_from_zendesk:
    default: false
  zendesk_tags:
    type: list
    client: false
    default: ''
